sudo: false

language: node_js

git:
    depth: false # Get all depth so our git-based version/change tracking of policies works

node_js:
    - "10"

script:
    - npm run ci-lint
    - npm run ci-test
    - make changelog
    - make policies
    - make -j$(nproc) travis-dist
    - mkdir -p out/dist-deploy/travis/${TRAVIS_BRANCH}
    - mkdir -p out/dist-deploy/cdn
    - cp -R out/dist-bin/* out/dist-deploy/travis/${TRAVIS_BRANCH}
    - cp -R out/dist/dist/* out/dist-deploy/cdn

deploy:
    on:
        all_branches:
            true
    provider: s3
    bucket: "compiler-explorer"
    skip_cleanup: true
    acl: public_read
    local_dir: out/dist-deploy
    upload-dir: dist

after_success: npm run codecov
