sudo: false

language: node_js

node_js:
    - "10"

script:
    - npm run ci-lint
    - npm run ci-test
    - make changelog
    - make policies
    - make -j$(nproc) travis-dist

deploy:
    on:
        all_branches:
            true
    provider: s3
    bucket: "compiler-explorer"
    skip_cleanup: true
    acl: public_read
    local_dir: out/dist-bin
    upload-dir: dist/travis/${TRAVIS_BRANCH}

after_success: npm run codecov
