[package]
name = "rustfilt"
version = "0.1.1"
authors = ["Matt Godbolt <matt@godbolt.org>"]

[dependencies]
rustc-demangle = "*"
regex = "*"
lazy_static = "*"

[features]
simd-accel = ["regex/simd-accel"]
